name: eda_llm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.3.3
  - matplotlib-base=3.10.6
  - seaborn=0.13.2
  - plotly=6.3.1
  - streamlit
  - scikit-learn
  - python-dotenv
  - requests
  - numpy
  - pip
  - pip:
      - openai==2.1.0
      - tiktoken
      - tenacity