name: eda_llm_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - seaborn
  - plotly
  - streamlit
  - scikit-learn
  - python-dotenv
  - numpy
  - requests
  - pip
  - pip:
      - matplotlib
      - openai==2.1.0
      - tiktoken
      - tenacity